"""empty message

Revision ID: 56958c48574a
Revises: 2cfd396813df
Create Date: 2021-03-29 16:04:48.770226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56958c48574a'
down_revision = '2cfd396813df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('transmission', sa.String(length=255), nullable=True),
    sa.Column('drive_unit', sa.String(length=255), nullable=True),
    sa.Column('engen', sa.String(length=255), nullable=True),
    sa.Column('type_engen', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('year', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avto')
    # ### end Alembic commands ###
