"""empty message

Revision ID: dd2d72943942
Revises: 56958c48574a
Create Date: 2021-04-15 14:38:59.934334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2d72943942'
down_revision = '56958c48574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ru_eng', sa.Column('context', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ru_eng', 'context')
    # ### end Alembic commands ###
